#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Lang {
    En,
    Ru,
}

impl Lang {
    pub fn parse(s: &str) -> Lang {
        if s.eq_ignore_ascii_case("ru") {
            Lang::Ru
        } else {
            Lang::En
        }
    }

    pub fn code(self) -> &'static str {
        match self {
            Lang::En => "en",
            Lang::Ru => "ru",
        }
    }

    pub fn toggled(self) -> Lang {
        match self {
            Lang::En => Lang::Ru,
            Lang::Ru => Lang::En,
        }
    }

    /// Форматирует смещение от UTC в минутах в «UTC±H:MM».
    pub fn format_tz_offset(self, offset_min: i32) -> String {
        let t = tr(self);
        let sign = if offset_min < 0 { "-" } else { "+" };
        let abs = offset_min.unsigned_abs();
        let h = abs / 60;
        let m = abs % 60;
        t.tz_label.replace("{sign}", sign).replace("{h}", &h.to_string()).replace("{m:02}", &format!("{:02}", m))
    }

    pub fn format_minutes(self, min: i32) -> String {
        format!("{:02}:{:02}", min / 60, min % 60)
    }
}

pub struct T {
    // Buttons
    pub btn_manage: &'static str,
    pub btn_add_map: &'static str,
    pub btn_add_host: &'static str,
    pub btn_add_name: &'static str,
    pub btn_add_all: &'static str,
    pub btn_notif_on: &'static str,
    pub btn_notif_off: &'static str,
    pub btn_lang: &'static str,
    pub btn_enable: &'static str,
    pub btn_disable: &'static str,
    pub btn_rename: &'static str,
    pub btn_delete: &'static str,
    pub btn_to_manage: &'static str,
    pub btn_menu: &'static str,
    pub btn_cancel: &'static str,
    pub btn_done: &'static str,
    // Welcome / status
    pub welcome: &'static str,
    pub st_hdr: &'static str,
    pub st_notifications: &'static str,
    pub st_enabled: &'static str,
    pub st_disabled: &'static str,
    pub st_forever: &'static str,
    pub st_remaining: &'static str,
    pub st_h: &'static str,
    pub st_m: &'static str,
    // Manage screen
    pub manage_hint: &'static str,
    pub manage_empty: &'static str,
    // Subscription view
    pub sub_id: &'static str, // {id}
    pub sub_name: &'static str,
    pub sub_type: &'static str,
    pub sub_status: &'static str,
    pub sub_enabled: &'static str,
    pub sub_disabled: &'static str,
    pub sub_desc_map: &'static str,
    pub sub_desc_host: &'static str,
    pub sub_desc_name: &'static str,
    pub kind_map: &'static str,
    pub kind_host: &'static str,
    pub kind_name: &'static str,
    // Prompts
    pub prompt_add_map: &'static str,
    pub prompt_add_host: &'static str,
    pub prompt_add_name: &'static str,
    pub prompt_add_all: &'static str,
    pub prompt_rename: &'static str, // {name}
    // Messages
    pub msg_cancelled: &'static str,
    pub msg_empty_name: &'static str,
    pub msg_duplicate: &'static str,
    pub msg_rename_fail: &'static str,
    pub msg_added: &'static str,   // {icon} {name}
    pub msg_deleted: &'static str, // {name}
    pub msg_use_menu: &'static str,
    pub msg_stop: &'static str,
    pub msg_add_more: &'static str,
    // Pinger
    pub ping_map: &'static str,     // {map}
    pub ping_name: &'static str,    // {name} {server}
    pub ping_host: &'static str,    // {host}
    pub ping_slots: &'static str,   // {taken} {total}
    pub ping_created: &'static str, // {time}
    pub ping_started: &'static str, // {time}
    pub dash: &'static str,         // empty name placeholder
    pub msg_add_all_done: &'static str, // {name} {list}
    // Notification keyboard
    pub btn_snooze: &'static str,
    pub btn_mute: &'static str,
    pub btn_check: &'static str,
    pub msg_snoozed: &'static str,
    pub msg_muted: &'static str,
    // Host filter
    pub btn_hosts: &'static str,
    pub hf_title: &'static str,      // {name}
    pub hf_mode: &'static str,
    pub hf_mode_off: &'static str,
    pub hf_mode_wl: &'static str,
    pub hf_mode_bl: &'static str,
    pub hf_hosts_hdr: &'static str,
    pub hf_hosts_empty: &'static str,
    pub btn_toggle_mode: &'static str,
    pub btn_add_hf_host: &'static str,
    pub prompt_add_hf_host: &'static str,
    pub msg_hf_host_added: &'static str,   // {host}
    pub msg_hf_host_deleted: &'static str, // {host}
    pub hf_desc_wl: &'static str,
    pub hf_desc_bl: &'static str,
    // Quiet hours / settings menu
    pub btn_settings: &'static str,
    pub btn_quiet: &'static str,
    pub quiet_title: &'static str,         // {start} {end} {tz}
    pub quiet_on: &'static str,
    pub quiet_off: &'static str,
    pub qh_now_in: &'static str,
    pub qh_now_out: &'static str,
    pub quiet_disabled: &'static str,
    pub btn_quiet_setup: &'static str,
    pub btn_quiet_disable: &'static str,
    pub btn_quiet_back: &'static str,
    pub prompt_qh_start: &'static str,
    pub prompt_qh_end: &'static str,
    pub prompt_qh_tz: &'static str,
    pub msg_qh_bad_time: &'static str,
    pub msg_qh_bad_tz: &'static str,
    pub msg_qh_invalid_range: &'static str,
    pub msg_qh_saved: &'static str, // {start} {end} {tz}
    pub msg_qh_disabled: &'static str,
    pub st_quiet_hdr: &'static str,
    pub st_subs_hdr: &'static str,
    pub tz_label: &'static str, // {sign}{h}:{m:02}
    // Min-players gate (per subscription)
    pub btn_players: &'static str,        // кнопка в карте
    pub pm_mini_hdr: &'static str,        // заголовок в sub_view: "Режим оповещений"
    pub pm_mini_off: &'static str,        // {n} — «Off (any count)»
    pub pm_mini_gate: &'static str,       // {n} — «Gate, N+ players»
    pub pm_mini_alert: &'static str,      // {n} — «Alert, N+ players, ×K repeats»
    pub pm_title: &'static str,           // {name} {kind}
    pub pm_mode: &'static str,
    pub pm_mode_off: &'static str,
    pub pm_mode_gate: &'static str,
    pub pm_mode_alert: &'static str,
    pub pm_mode_desc_off: &'static str,
    pub pm_mode_desc_gate: &'static str,
    pub pm_mode_desc_alert: &'static str,
    pub pm_threshold: &'static str,        // {n}
    pub pm_alert_count: &'static str,      // {n}
    pub pm_alert_count_hint: &'static str, // подпись «сколько раз продублировать»
    pub pm_alert_count_dec: &'static str,
    pub pm_alert_count_inc: &'static str,
    pub pm_help: &'static str,             // краткое объяснение
    pub pm_pick_number: &'static str,
    pub pm_custom: &'static str,           // «+» на всю ширину
    pub prompt_pm_custom: &'static str,    // {min} {max}
    pub msg_pm_invalid: &'static str,      // {min} {max}
    pub msg_pm_alert_extra: &'static str,  // {n} {map} для доп. оповещения
    // Monitor (per-user nickname/explicit watching of one's own hosted games)
    pub btn_monitor: &'static str,
    pub btn_monitor_watch: &'static str,
    pub monitor_title: &'static str,
    pub monitor_state_on: &'static str,
    pub monitor_state_off: &'static str,
    pub monitor_no_identity: &'static str,
    pub monitor_current_identity: &'static str,
    pub btn_monitor_set: &'static str,
    pub btn_monitor_change: &'static str,
    pub btn_monitor_disable: &'static str,
    pub btn_monitor_enable: &'static str,
    pub prompt_monitor_nick: &'static str,
    pub msg_monitor_invalid: &'static str,
    pub msg_monitor_set: &'static str,
    pub msg_monitor_toggled: &'static str,
    pub monitor_active_hdr: &'static str,
    pub monitor_active_none: &'static str,
    pub monitor_active_item: &'static str,
    pub msg_monitor_started_explicit: &'static str,
    pub msg_monitor_started_nickname: &'static str,
    pub msg_monitor_plus: &'static str,
    pub msg_monitor_minus: &'static str,
    pub msg_monitor_filled: &'static str,
}

const EN: T = T {
    btn_manage: "📊 View & Manage",
    btn_add_map: "➕ Map",
    btn_add_host: "➕ 👤 Host",
    btn_add_name: "➕ 📛 Name",
    btn_add_all: "➕ ✨ All types",
    btn_notif_on: "🔔 Notifications: ✅ on",
    btn_notif_off: "🔕 Notifications: ❌ off",
    btn_lang: "🌐 Language: English",
    btn_enable: "✅ Enable",
    btn_disable: "❌ Disable",
    btn_rename: "✏️ Rename",
    btn_delete: "🗑 Delete",
    btn_to_manage: "⬅️ Back",
    btn_menu: "🏠 Main menu",
    btn_cancel: "↩️ Cancel",
    btn_done: "✅ Done",
    welcome: "👋 Hi! I watch WarCraft 3 lobbies on wc3stats.\n\n\
              Add a subscription for a map or a host — I'll message you when a new lobby appears.\n\n\
              Names are matched case- and symbol-insensitively: \
              \u{00ab}CHS\u{00bb} matches both \u{00ab}CHS -\u{00bb} and \u{00ab}something*chs*\u{00bb}.\n\n\
              ⚙️ More features in \u{00ab}Settings\u{00ab}.",
    st_hdr: "📊 Status:",
    st_notifications: "Notifications",
    st_enabled: "✅ Enabled",
    st_disabled: "❌ Disabled",
    st_forever: "forever",
    st_remaining: "left",
    st_h: "h",
    st_m: "m",
    manage_hint: "\nTap a button below to edit.",
    manage_empty: "No subscriptions yet.",
    sub_id: "Subscription #{id}",
    sub_name: "Name",
    sub_type: "Type",
    sub_status: "Status",
    sub_enabled: "✅ Enabled",
    sub_disabled: "❌ Disabled",
    sub_desc_map: "Notifications are sent when a new lobby's map name contains this name (case- and symbol-insensitive).",
    sub_desc_host: "Notifications are sent when a new lobby's host name contains this name (case- and symbol-insensitive).",
    sub_desc_name: "Notifications are sent when a new lobby's game name contains this name (case- and symbol-insensitive).",
    kind_map: "🗺 Map",
    kind_host: "👤 Host",
    kind_name: "📛 Name",
    prompt_add_map: "🗺 Send me the map name to track.\n\nExamples: pudge, chs, legion td",
    prompt_add_host: "👤 Send me the host name to track.\n\nExamples: HellWolf#31976, hellwolf\n\n⚠️ Host subscriptions don't support whitelist/blacklist.",
    prompt_add_name: "📛 Send me the game name to track.\n\nExamples: dota, tavern, fun",
    prompt_add_all: "✨ Send me a name — I'll subscribe you to map, host, and game name at once.\n\n⚠️ Combined subscriptions don't support whitelist/blacklist.",
    prompt_rename: "✏️ Current name: \u{00ab}{name}\u{00bb}\n\nSend me the new name:",
    msg_cancelled: "↩️ Cancelled.",
    msg_empty_name: "⚠️ Name cannot be empty. Try again:",
    msg_duplicate: "⚠️ Such subscription already exists.",
    msg_rename_fail: "⚠️ Failed to rename. Try again:",
    msg_added: "{icon} Subscription \u{00ab}{name}\u{00bb} added!",
    msg_deleted: "🗑 Subscription \u{00ab}{name}\u{00bb} deleted.",
    msg_use_menu: "🤔 Use the menu buttons or /start.",
    msg_stop: "👋 All your data has been deleted. /start to start over.",
    msg_add_more: "Send another name or press Done to finish.",
    ping_map: "🗺️ Map: {map}",
    ping_name: "📛 Name: {name} ({server})",
    ping_host: "🏠 Host: {host}",
    ping_slots: "👥 Players: {taken}/{total}",
    ping_created: "⏱ Created: {time} ago",
    ping_started: "✅ Started: after {time}",
    dash: "—",
    msg_add_all_done: "✅ {name} — {list}\n\n{more}",
    btn_snooze: "😴 12h",
    btn_mute: "🔕 Off",
    btn_check: "✅",
    msg_snoozed: "🔕 Notifications off for 12 hours",
    msg_muted: "🔕 Notifications turned off",
    btn_hosts: "⚙️ Hosts",
    hf_title: "⚙️ Host filter: {name}",
    hf_mode: "Mode",
    hf_mode_off: "Off",
    hf_mode_wl: "Whitelist",
    hf_mode_bl: "Blacklist",
    hf_hosts_hdr: "Hosts",
    hf_hosts_empty: "No hosts added",
    btn_toggle_mode: "🔄 Toggle mode",
    btn_add_hf_host: "➕ Add host",
    prompt_add_hf_host: "👤 Send the host name to add to the filter.\n\nExamples: HellWolf#31976, hellwolf",
    msg_hf_host_added: "✅ Host \u{00ab}{host}\u{00bb} added.",
    msg_hf_host_deleted: "🗑 Host \u{00ab}{host}\u{00bb} removed.",
    hf_desc_wl: "Only notify when the host is in the list.",
    hf_desc_bl: "Skip games hosted by players in the list.",
    btn_settings: "⚙️ Settings",
    btn_quiet: "⏰ Notification window",
    quiet_title: "⏰ Notification window: {start}–{end} ({tz})",
    quiet_on: "{start}–{end}",
    quiet_off: "All time",
    qh_now_in: "🔔 Now in window — notifications allowed",
    qh_now_out: "🔕 Outside window — notifications paused",
    quiet_disabled: "⏰ No notification window set.\n\nNotifications are sent at any time.",
    btn_quiet_setup: "✏️ Set up",
    btn_quiet_disable: "🔕 Turn off",
    btn_quiet_back: "⬅️ Back",
    prompt_qh_start: "⏰ Send the start time in HH:MM format.\n\nExample: 07:00",
    prompt_qh_end: "⏰ Send the end time in HH:MM format.\n\nExample: 23:00 (can be earlier than the start — e.g. 23:00–07:00).",
    prompt_qh_tz: "⏰ Send your UTC offset, e.g. UTC+3, UTC-5, UTC+5:30 — or simply +3, -5, +5:30.",
    msg_qh_bad_time: "⚠️ Invalid time. Use HH:MM, e.g. 23:00.",
    msg_qh_bad_tz: "⚠️ Invalid UTC offset. Example: UTC+3 or UTC-5:30.",
    msg_qh_invalid_range: "⚠️ Start and end times must be different.",
    msg_qh_saved: "✅ Notification window saved: {start}–{end} ({tz}).",
    msg_qh_disabled: "🔕 Notification window disabled.",
    st_quiet_hdr: "Notification window",
    st_subs_hdr: "Your subscriptions",
    tz_label: "{sign}{h}:{m:02}",
    btn_players: "🎮 Min players",
    pm_mini_hdr: "🔔 Notify mode",
    pm_mini_off: "Off — ping on every matching lobby",
    pm_mini_gate: "Threshold — ping only when the lobby has {n}+ players",
    pm_mini_alert: "Alert — ping on every matching lobby, plus a reminder at {n}+ players (×{k})",
    pm_title: "🎮 Min players: {kind} \u{00ab}{name}\u{00bb}",
    pm_mode: "Mode",
    pm_mode_off: "Off",
    pm_mode_gate: "Threshold",
    pm_mode_alert: "Alert",
    pm_mode_desc_off: "Disabled — you get a ping for every matching lobby.",
    pm_mode_desc_gate: "Wait — pings only after the lobby has at least N players.",
    pm_mode_desc_alert: "You get a ping for every matching lobby, plus an extra reminder when the lobby reaches N players.",
    pm_threshold: "Threshold",
    pm_alert_count: "Alert repeats: {n}",
    pm_alert_count_hint: "How many extra messages to send in Alert mode.",
    pm_alert_count_dec: "➖",
    pm_alert_count_inc: "➕",
    pm_help: "How it works:\n• Off — pings for every matching lobby.\n• Threshold — pings only after the lobby has at least N players.\n• Alert — pings for every matching lobby, plus an extra reminder when the lobby reaches N players.",
    pm_pick_number: "Pick a threshold (1–12), or tap ✏️ to enter your own (1–24):",
    pm_custom: "✏️ Custom…",
    prompt_pm_custom: "Send the minimum number of players (1–24).",
    msg_pm_invalid: "⚠️ Enter a number between {min} and {max}.",
    msg_pm_alert_extra: "🔥 {n} players on \u{00ab}{map}\u{00bb} — jump in!",
    btn_monitor: "👁 Monitor",
    btn_monitor_watch: "👁 Watch",
    monitor_title: "👁 Monitor your games\n\nNotifies you when players join or leave your lobbies — ones you host (by identity) or ones you pick to watch (from a notification).",
    monitor_state_on: "Enabled",
    monitor_state_off: "Disabled",
    monitor_no_identity: "Not set — tap «Set identity» to begin.",
    monitor_current_identity: "Your identity: \u{00ab}{id}\u{00bb}",
    btn_monitor_set: "✏️ Set identity",
    btn_monitor_change: "✏️ Change identity",
    btn_monitor_disable: "🔕 Disable",
    btn_monitor_enable: "✅ Enable",
    prompt_monitor_nick: "👁 Send your WC3 identity in the format \u{00ab}Name#12345\u{00bb}.\n\nExample: Rutex#2561\n\nThe id part must be digits only.",
    msg_monitor_invalid: "⚠️ Invalid format. Expected \u{00ab}Name#12345\u{00bb} (digits only after #).",
    msg_monitor_set: "✅ Identity set: \u{00ab}{id}\u{00bb}",
    msg_monitor_toggled: "🔄 Monitoring: {state}",
    monitor_active_hdr: "Active explicit watches",
    monitor_active_none: "No active watches.",
    monitor_active_item: "• {map} by {host} — {taken}/{total}",
    msg_monitor_started_explicit: "👁 Watching lobby \u{00ab}{map}\u{00ab} by {host} — {taken}/{total} (free: {free})",
    msg_monitor_started_nickname: "👁 I see you in lobby \u{00ab}{map}\u{00ab} by {host} — {taken}/{total} (free: {free})",
    msg_monitor_plus: "➕ {n} joined ({taken}/{total}, free: {free})",
    msg_monitor_minus: "➖ {n} left ({taken}/{total}, free: {free})",
    msg_monitor_filled: "🔥 Lobby is full! ({taken}/{total}, free: {free})",
};

const RU: T = T {
    btn_manage: "📊 Статус и управление",
    btn_add_map: "➕ Карта",
    btn_add_host: "➕ 👤 Хост",
    btn_add_name: "➕ 📛 Название",
    btn_add_all: "➕ ✨ Все типы",
    btn_notif_on: "🔔 Уведомления: ✅ вкл",
    btn_notif_off: "🔕 Уведомления: ❌ выкл",
    btn_lang: "🌐 Язык: Русский",
    btn_enable: "✅ Включить",
    btn_disable: "❌ Выключить",
    btn_rename: "✏️ Переименовать",
    btn_delete: "🗑 Удалить",
    btn_to_manage: "⬅️ Назад",
    btn_menu: "🏠 Главное меню",
    btn_cancel: "↩️ Отмена",
    btn_done: "✅ Готово",
    welcome: "👋 Привет! Я слежу за игровыми лобби WarCraft 3 на wc3stats.\n\n\
              Добавь подписку на карту или хоста — и я пришлю уведомление, \
              когда появится новое лобби.\n\n\
              Названия сравниваются без учёта регистра и символов: \
              «CHS» совпадёт и с «CHS -», и с «something*chs*».\n\n\
              ⚙️ Дополнительные возможности — в «Настройках».",
    st_hdr: "📊 Статус:",
    st_notifications: "Уведомления",
    st_enabled: "✅ Включены",
    st_disabled: "❌ Выключены",
    st_forever: "навсегда",
    st_remaining: "осталось",
    st_h: "ч",
    st_m: "мин",
    manage_hint: "\nНажми кнопку ниже, чтобы изменить.",
    manage_empty: "Подписок пока нет.",
    sub_id: "Подписка #{id}",
    sub_name: "Название",
    sub_type: "Тип",
    sub_status: "Статус",
    sub_enabled: "✅ Включена",
    sub_disabled: "❌ Выключена",
    sub_desc_map: "Уведомления приходят, когда имя карты в новом лобби содержит это название (без учёта регистра и символов).",
    sub_desc_host: "Уведомления приходят, когда имя хоста в новом лобби содержит это название (без учёта регистра и символов).",
    sub_desc_name: "Уведомления приходят, когда название игры в новом лобби содержит это название (без учёта регистра и символов).",
    kind_map: "🗺 Карта",
    kind_host: "👤 Хост",
    kind_name: "📛 Название",
    prompt_add_map: "🗺 Отправь название карты для отслеживания.\n\nПримеры: pudge, chs, legion td",
    prompt_add_host: "👤 Отправь имя хоста для отслеживания.\n\nПримеры: HellWolf#31976, hellwolf\n\n⚠️ Подписки для хоста не поддерживают белый/чёрный список.",
    prompt_add_name: "📛 Отправь название игры для отслеживания.\n\nПримеры: dota, tavern, fun",
    prompt_add_all: "✨ Отправь название — я подпишу на карту, хоста и название игры сразу.\n\n⚠️ Общие подписки не поддерживают белый/чёрный список.",
    prompt_rename: "✏️ Текущее название: «{name}»\n\nОтправь новое название:",
    msg_cancelled: "↩️ Отменено.",
    msg_empty_name: "⚠️ Название не может быть пустым. Попробуй ещё раз:",
    msg_duplicate: "⚠️ Такая подписка уже существует.",
    msg_rename_fail: "⚠️ Не удалось переименовать. Попробуй ещё раз:",
    msg_added: "{icon} Подписка «{name}» добавлена!",
    msg_deleted: "🗑 Подписка «{name}» удалена.",
    msg_use_menu: "🤔 Используй кнопки меню или /start.",
    msg_stop: "👋 Все твои данные удалены. /start — начать заново.",
    msg_add_more: "Отправь ещё одно название или нажми Готово.",
    ping_map: "🗺️ Карта: {map}",
    ping_name: "📛 Название: {name} ({server})",
    ping_host: "🏠 Хост: {host}",
    ping_slots: "👥 Игроки: {taken}/{total}",
    ping_created: "⏱ Создано: {time} назад",
    ping_started: "✅ Началось: спустя {time}",
    dash: "—",
    msg_add_all_done: "✅ {name} — {list}\n\n{more}",
    btn_snooze: "😴 12ч",
    btn_mute: "🔕 Выкл",
    btn_check: "✅",
    msg_snoozed: "🔕 Уведомления выключены на 12 часов",
    msg_muted: "🔕 Уведомления выключены",
    btn_hosts: "⚙️ Хосты",
    hf_title: "⚙️ Фильтр хостов: {name}",
    hf_mode: "Режим",
    hf_mode_off: "Выкл",
    hf_mode_wl: "Белый список",
    hf_mode_bl: "Чёрный список",
    hf_hosts_hdr: "Хосты",
    hf_hosts_empty: "Хостов нет",
    btn_toggle_mode: "🔄 Сменить режим",
    btn_add_hf_host: "➕ Добавить хоста",
    prompt_add_hf_host: "👤 Отправь имя хоста для добавления в фильтр.\n\nПримеры: HellWolf#31976, hellwolf",
    msg_hf_host_added: "✅ Хост «{host}» добавлен.",
    msg_hf_host_deleted: "🗑 Хост «{host}» удалён.",
    hf_desc_wl: "Уведомлять только если хост в списке.",
    hf_desc_bl: "Пропускать игры от хостов из списка.",
    btn_settings: "⚙️ Настройки",
    btn_quiet: "⏰ Время уведомлений",
    quiet_title: "⏰ Время уведомлений: {start}–{end} ({tz})",
    quiet_on: "{start}–{end}",
    quiet_off: "Всё время",
    qh_now_in: "🔔 В окне — уведомления приходят",
    qh_now_out: "🔕 Вне окна — уведомления приостановлены",
    quiet_disabled: "⏰ Окно уведомлений не настроено.\n\nУведомления приходят в любое время.",
    btn_quiet_setup: "✏️ Настроить",
    btn_quiet_disable: "🔕 Выключить",
    btn_quiet_back: "⬅️ Назад",
    prompt_qh_start: "⏰ Отправь время начала в формате HH:MM.\n\nНапример: 07:00",
    prompt_qh_end: "⏰ Отправь время конца в формате HH:MM.\n\nНапример: 23:00 (может быть раньше начала — например, 23:00–07:00).",
    prompt_qh_tz: "⏰ Отправь своё смещение от UTC, например UTC+3, UTC-5, UTC+5:30 — или коротко: +3, -5, +5:30.",
    msg_qh_bad_time: "⚠️ Неверное время. Используй HH:MM, например 23:00.",
    msg_qh_bad_tz: "⚠️ Неверное смещение от UTC. Пример: UTC+3 или UTC-5:30.",
    msg_qh_invalid_range: "⚠️ Время начала и конца должны различаться.",
    msg_qh_saved: "✅ Время уведомлений сохранено: {start}–{end} ({tz}).",
    msg_qh_disabled: "🔕 Время уведомлений выключено.",
    st_quiet_hdr: "Время уведомлений",
    st_subs_hdr: "Твои подписки",
    tz_label: "{sign}{h}:{m:02}",
    btn_players: "🎮 Мин. игроков",
    pm_mini_hdr: "🔔 Режим оповещений",
    pm_mini_off: "Выкл — пинг о каждом подходящем лобби",
    pm_mini_gate: "Порог — пинг только когда в лобби {n}+ игроков",
    pm_mini_alert: "Алерт — пинг о каждом подходящем лобби, плюс напоминание на {n}+ игроках (×{k})",
    pm_title: "🎮 Мин. игроков: {kind} «{name}»",
    pm_mode: "Режим",
    pm_mode_off: "Выкл",
    pm_mode_gate: "Порог",
    pm_mode_alert: "Алерт",
    pm_mode_desc_off: "Выключено — пинг о каждом подходящем лобби.",
    pm_mode_desc_gate: "Ждём — пинг придёт только когда в лобби наберётся N игроков.",
    pm_mode_desc_alert: "Пинг о каждом подходящем лобби, плюс отдельное напоминание когда набралось N игроков.",
    pm_threshold: "Порог",
    pm_alert_count: "Повторов алерта: {n}",
    pm_alert_count_hint: "Сколько дополнительных сообщений слать в режиме «Алерт».",
    pm_alert_count_dec: "➖",
    pm_alert_count_inc: "➕",
    pm_help: "Как это работает:\n• Выкл — пинг о каждом подходящем лобби.\n• Порог — пинг только когда в лобби набралось N игроков.\n• Алерт — пинг о каждом подходящем лобби, плюс отдельное напоминание когда набралось N игроков.",
    pm_pick_number: "Выбери порог (1–12) или нажми ✏️, чтобы ввести свой (1–24):",
    pm_custom: "✏️ Свой…",
    prompt_pm_custom: "Отправь минимальное число игроков (1–24).",
    msg_pm_invalid: "⚠️ Введи число от {min} до {max}.",
    msg_pm_alert_extra: "🔥 {n} игроков на «{map}» — залетай!",
    btn_monitor: "👁 Мониторинг",
    btn_monitor_watch: "👁 Следить",
    monitor_title: "👁 Мониторинг своих игр\n\nУведомляет, когда кто-то заходит или выходит из твоих лобби — тех, что ты хостишь (по нику) или которые ты выбрал из уведомления.",
    monitor_state_on: "Включён",
    monitor_state_off: "Выключен",
    monitor_no_identity: "Не задан — нажми «Задать ник», чтобы начать.",
    monitor_current_identity: "Твой ник: «{id}»",
    btn_monitor_set: "✏️ Задать ник",
    btn_monitor_change: "✏️ Сменить ник",
    btn_monitor_disable: "🔕 Выключить",
    btn_monitor_enable: "✅ Включить",
    prompt_monitor_nick: "👁 Отправь свой WC3-ник в формате «Имя#12345».\n\nПример: Rutex#2561\n\nПосле # — только цифры.",
    msg_monitor_invalid: "⚠️ Неверный формат. Ожидается «Имя#12345» (после # только цифры).",
    msg_monitor_set: "✅ Ник задан: «{id}»",
    msg_monitor_toggled: "🔄 Мониторинг: {state}",
    monitor_active_hdr: "Активные слежки",
    monitor_active_none: "Нет активных слежек.",
    monitor_active_item: "• {map} от {host} — {taken}/{total}",
    msg_monitor_started_explicit: "👁 Слежу за лобби «{map}» от {host} — {taken}/{total} (свободно: {free})",
    msg_monitor_started_nickname: "👁 Вижу тебя в лобби «{map}» от {host} — {taken}/{total} (свободно: {free})",
    msg_monitor_plus: "➕ Зашли: {n} ({taken}/{total}, свободно: {free})",
    msg_monitor_minus: "➖ Вышли: {n} ({taken}/{total}, свободно: {free})",
    msg_monitor_filled: "🔥 Лобби заполнено! ({taken}/{total}, свободно: {free})",
};

pub fn tr(lang: Lang) -> &'static T {
    match lang {
        Lang::En => &EN,
        Lang::Ru => &RU,
    }
}
